// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh8GxNxCDsPDKIAA84ji252-JvzDWsqZ8',
    appId: '1:986012821030:web:069ecb0468c2c42eaaa8e7',
    messagingSenderId: '986012821030',
    projectId: 'shop-hub-7bcc8',
    authDomain: 'shop-hub-7bcc8.firebaseapp.com',
    storageBucket: 'shop-hub-7bcc8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2PBBVg_Iljh-pv8HcqClVq5jQ-32-Rag',
    appId: '1:986012821030:android:f5951bbde54796e2aaa8e7',
    messagingSenderId: '986012821030',
    projectId: 'shop-hub-7bcc8',
    storageBucket: 'shop-hub-7bcc8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUiRfqQXWhrYWWhGa1wZZEsQHhiDYufQ',
    appId: '1:986012821030:ios:056a344e06346b09aaa8e7',
    messagingSenderId: '986012821030',
    projectId: 'shop-hub-7bcc8',
    storageBucket: 'shop-hub-7bcc8.appspot.com',
    iosBundleId: 'com.example.shopHubAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUiRfqQXWhrYWWhGa1wZZEsQHhiDYufQ',
    appId: '1:986012821030:ios:056a344e06346b09aaa8e7',
    messagingSenderId: '986012821030',
    projectId: 'shop-hub-7bcc8',
    storageBucket: 'shop-hub-7bcc8.appspot.com',
    iosBundleId: 'com.example.shopHubAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh8GxNxCDsPDKIAA84ji252-JvzDWsqZ8',
    appId: '1:986012821030:web:9d465a7909049001aaa8e7',
    messagingSenderId: '986012821030',
    projectId: 'shop-hub-7bcc8',
    authDomain: 'shop-hub-7bcc8.firebaseapp.com',
    storageBucket: 'shop-hub-7bcc8.appspot.com',
  );
}
